Repository pivotal-cf/docs-ops-manager, pull requests merged in 2019-01, with the labels that each got.

#10 adding pks specific info [#162865058]
  azure/config-terraform.html.md.erb
Labels: in progress

#11 Fixed the CIDR for the proposed network resources
  azure/deploy-manual.html.md.erb
Labels: scheduled

#12 Fix Terraform output key name for AWS Secret Key
  aws/config-terraform.html.md.erb
Labels: scheduled

#15 Story 162865188
  common/_using_ldap_server_ops_manager.html.md.erb
  gcp/config-manual.html.md.erb
  gcp/prepare-env-manual.html.md.erb
  gcp/prepare-env-terraform.html.md.erb
Labels: in progress

#17 Story 163432622 2.2
  gcp/prepare-env-manual.html.md.erb
Labels: in progress

#21 Story 162865188 rej 001
  common/_using_ldap_server_ops_manager.html.md.erb
  gcp/config-manual.html.md.erb
  gcp/deploy-manual.html.md.erb
  gcp/prepare-env-manual.html.md.erb
Labels: unscheduled

#22 revise azure terraform link to terraform instead of manul [#163601694]
  azure/prepare-env-terraform.html.md.erb
Labels: unscheduled

#19 added instructions to allow for Private IP consumption.
  azure/deploy-manual.html.md.erb
Labels: unscheduled
