Repository pivotal-cf/docs-ops-manager, pull requests merged in 2020-12, with the labels that each got.

#111 Update _director-config.html.md.erb
  common/_director-config.html.md.erb
Labels: in progress

#113 Remove duplicate breaking change for OM 2.10
  release-notes.html.md.erb
Labels: scheduled

#115 Remove old command
  security/pcf-infrastructure/advanced-certificate-rotation.html.md.erb
Labels: scheduled

#116 Add note about internal blobstore TLS to jump upgrades docs
  jump-upgrades.html.md.erb
Labels: unscheduled
