Repository pivotal-cf/docs-ops-manager, pull requests merged in 2020-11, with the labels that each got.

#105 Adding error message from crash
  release-notes.html.md.erb
Labels: scheduled

#107 clarify three-legged rotation
  security/pcf-infrastructure/rotate-cas-and-leaf-certs.html.md.erb
Labels: in progress

#106 Update NSX-T Certificate Auth config instructions
  vsphere/config.html.md.erb
Labels: scheduled

#108 Document missing bug fix around BOSH DNS cert rotation in 2.9.0
  release-notes.html.md.erb
Labels: scheduled

#109 Documents Blobstore IAM Profile option
  common/_blobstore-location.html.md.erb
Labels: unscheduled

#104 Update release notes and upgrade checklist for using Azure Generation 2 VM types
  azure/config-manual.html.md.erb
  release-notes.html.md.erb
  upgrade/checklist.html.md.erb
Labels: in progress

#110 Update nats-network-paths.html.md.erb
  security/networking/nats-network-paths.html.md.erb
Labels: scheduled

#112 Update _director-config.html.md.erb
  common/_director-config.html.md.erb
Labels: scheduled
