Repository pivotal-cf/docs-ops-manager, pull requests merged in 2021-01, with the labels that each got.

#119 Updates NTP server guidance on Azure
  common/_director-config.html.md.erb
Labels: scheduled

#117 Updates NTP server guidance on Azure
  common/_director-config.html.md.erb
Labels: scheduled

#118 Updates NTP server guidance on Azure
  common/_director-config.html.md.erb
Labels: scheduled

#126 Swapping order to match page
  aws/deploy-manual.html.md.erb
Labels: scheduled

#125 Update current defaults
  aws/deploy-manual.html.md.erb
Labels: scheduled

#124 Default vm size change
  aws/deploy-manual.html.md.erb
Labels: scheduled

#123 Security group rules default change
  aws/prepare-env-manual.html.md.erb
Labels: scheduled

#120 Update config-manual.html.md.erb
  aws/config-manual.html.md.erb
Labels: in progress

#122 Verbage change to VPC wizard
  aws/prepare-env-manual.html.md.erb
Labels: scheduled

#121 Remove uneccessary line
  aws/prepare-env-manual.html.md.erb
Labels: scheduled

#127 Fix unknown option for jq
  security/pcf-infrastructure/manual-credhub-certificate.html.md.erb
Labels: scheduled

#128 Update deploy-manual.html.md.erb
  aws/deploy-manual.html.md.erb
Labels: unscheduled

#131 Update deploy-manual.html.md.erb
  aws/deploy-manual.html.md.erb
Labels: unscheduled

#130 Update deploy-manual.html.md.erb
  aws/deploy-manual.html.md.erb
Labels: unscheduled

#129 Update deploy-manual.html.md.erb
  aws/deploy-manual.html.md.erb
Labels: unscheduled

#132 Update deploy-manual.html.md.erb
  aws/deploy-manual.html.md.erb
Labels: unscheduled

#133 Add note on purging MySQL service instance in failover situation
  install/backup-restore/restore-pcf-bbr.html.md.erb
Labels: scheduled
